// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateApiKeyData, CreateApiKeyErrors, CreateApiKeyResponses, DeleteApiKeyData, DeleteApiKeyErrors, DeleteApiKeyResponses, GetApiKeyInfoData, GetApiKeyInfoErrors, GetApiKeyInfoResponses, GetEventData, GetEventErrors, GetEventResponses, GetGlobalPnlData, GetGlobalPnlErrors, GetGlobalPnlResponses, GetHealthStatusData, GetHealthStatusResponses, GetMarketBySlugData, GetMarketBySlugErrors, GetMarketBySlugResponses, GetMarketCandlestickData, GetMarketCandlestickErrors, GetMarketCandlestickResponses, GetMarketData, GetMarketErrors, GetMarketResponses, GetOrderBookData, GetOrderBookErrors, GetOrderBookResponses, GetTraderPnlData, GetTraderPnlErrors, GetTraderPnlResponses, ListEventsData, ListEventsErrors, ListEventsResponses, ListMarketHoldersData, ListMarketHoldersErrors, ListMarketHoldersResponses, ListMarketsData, ListMarketsErrors, ListMarketsResponses, ListMarketTradesData, ListMarketTradesErrors, ListMarketTradesResponses, ListTraderPositionsData, ListTraderPositionsErrors, ListTraderPositionsResponses, ListTraderTradesData, ListTraderTradesErrors, ListTraderTradesResponses, ListUserKeysData, ListUserKeysErrors, ListUserKeysResponses, SearchData, SearchErrors, SearchResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class Authentication {
    /**
     * List the current user's API keys
     */
    public static listUserKeys<ThrowOnError extends boolean = false>(options?: Options<ListUserKeysData, ThrowOnError>): RequestResult<ListUserKeysResponses, ListUserKeysErrors, ThrowOnError> {
        return (options?.client ?? client).get<ListUserKeysResponses, ListUserKeysErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/keys',
            ...options
        });
    }
    
    /**
     * Create an API key
     */
    public static createApiKey<ThrowOnError extends boolean = false>(options: Options<CreateApiKeyData, ThrowOnError>): RequestResult<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError> {
        return (options.client ?? client).post<CreateApiKeyResponses, CreateApiKeyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/keys',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
    
    /**
     * Delete an API key
     */
    public static deleteApiKey<ThrowOnError extends boolean = false>(options: Options<DeleteApiKeyData, ThrowOnError>): RequestResult<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError> {
        return (options.client ?? client).delete<DeleteApiKeyResponses, DeleteApiKeyErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/auth/keys/{keyLabel}',
            ...options
        });
    }
    
    /**
     * Get current API key info
     */
    public static getApiKeyInfo<ThrowOnError extends boolean = false>(options?: Options<GetApiKeyInfoData, ThrowOnError>): RequestResult<GetApiKeyInfoResponses, GetApiKeyInfoErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetApiKeyInfoResponses, GetApiKeyInfoErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/auth/me',
            ...options
        });
    }
}

export class Health {
    /**
     * Get health status
     */
    public static getHealthStatus<ThrowOnError extends boolean = false>(options?: Options<GetHealthStatusData, ThrowOnError>): RequestResult<GetHealthStatusResponses, unknown, ThrowOnError> {
        return (options?.client ?? client).get<GetHealthStatusResponses, unknown, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/health',
            ...options
        });
    }
}

export class Events {
    /**
     * List events
     */
    public static listEvents<ThrowOnError extends boolean = false>(options?: Options<ListEventsData, ThrowOnError>): RequestResult<ListEventsResponses, ListEventsErrors, ThrowOnError> {
        return (options?.client ?? client).get<ListEventsResponses, ListEventsErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/events',
            ...options
        });
    }
    
    /**
     * Get an event by id or slug
     */
    public static getEvent<ThrowOnError extends boolean = false>(options: Options<GetEventData, ThrowOnError>): RequestResult<GetEventResponses, GetEventErrors, ThrowOnError> {
        return (options.client ?? client).get<GetEventResponses, GetEventErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/events/{identifier}',
            ...options
        });
    }
}

export class Markets {
    /**
     * List markets by volume
     */
    public static listMarkets<ThrowOnError extends boolean = false>(options?: Options<ListMarketsData, ThrowOnError>): RequestResult<ListMarketsResponses, ListMarketsErrors, ThrowOnError> {
        return (options?.client ?? client).get<ListMarketsResponses, ListMarketsErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/markets',
            ...options
        });
    }
    
    /**
     * Get a market by slug
     */
    public static getMarketBySlug<ThrowOnError extends boolean = false>(options: Options<GetMarketBySlugData, ThrowOnError>): RequestResult<GetMarketBySlugResponses, GetMarketBySlugErrors, ThrowOnError> {
        return (options.client ?? client).get<GetMarketBySlugResponses, GetMarketBySlugErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/markets/slug/{market_slug}',
            ...options
        });
    }
    
    /**
     * Get a market by condition id
     */
    public static getMarket<ThrowOnError extends boolean = false>(options: Options<GetMarketData, ThrowOnError>): RequestResult<GetMarketResponses, GetMarketErrors, ThrowOnError> {
        return (options.client ?? client).get<GetMarketResponses, GetMarketErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/markets/{condition_id}',
            ...options
        });
    }
    
    /**
     * OHLC candlesticks for a market
     */
    public static getMarketCandlestick<ThrowOnError extends boolean = false>(options: Options<GetMarketCandlestickData, ThrowOnError>): RequestResult<GetMarketCandlestickResponses, GetMarketCandlestickErrors, ThrowOnError> {
        return (options.client ?? client).get<GetMarketCandlestickResponses, GetMarketCandlestickErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/markets/{condition_id}/candlestick',
            ...options
        });
    }
    
    /**
     * Current holders for a market
     */
    public static listMarketHolders<ThrowOnError extends boolean = false>(options: Options<ListMarketHoldersData, ThrowOnError>): RequestResult<ListMarketHoldersResponses, ListMarketHoldersErrors, ThrowOnError> {
        return (options.client ?? client).get<ListMarketHoldersResponses, ListMarketHoldersErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/markets/{condition_id}/holders',
            ...options
        });
    }
    
    /**
     * List trades for a market
     */
    public static listMarketTrades<ThrowOnError extends boolean = false>(options: Options<ListMarketTradesData, ThrowOnError>): RequestResult<ListMarketTradesResponses, ListMarketTradesErrors, ThrowOnError> {
        return (options.client ?? client).get<ListMarketTradesResponses, ListMarketTradesErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/markets/{condition_id}/trades',
            ...options
        });
    }
}

export class OrderBook {
    /**
     * Order book midpoint for a position
     */
    public static getOrderBook<ThrowOnError extends boolean = false>(options: Options<GetOrderBookData, ThrowOnError>): RequestResult<GetOrderBookResponses, GetOrderBookErrors, ThrowOnError> {
        return (options.client ?? client).get<GetOrderBookResponses, GetOrderBookErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/order-book',
            ...options
        });
    }
}

export class Search {
    /**
     * Search markets and traders
     */
    public static search<ThrowOnError extends boolean = false>(options: Options<SearchData, ThrowOnError>): RequestResult<SearchResponses, SearchErrors, ThrowOnError> {
        return (options.client ?? client).get<SearchResponses, SearchErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/search',
            ...options
        });
    }
}

export class Traders {
    /**
     * PnL leaderboard
     */
    public static getGlobalPnl<ThrowOnError extends boolean = false>(options?: Options<GetGlobalPnlData, ThrowOnError>): RequestResult<GetGlobalPnlResponses, GetGlobalPnlErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetGlobalPnlResponses, GetGlobalPnlErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/traders/global-pnl',
            ...options
        });
    }
    
    /**
     * Trader PnL summary
     */
    public static getTraderPnl<ThrowOnError extends boolean = false>(options: Options<GetTraderPnlData, ThrowOnError>): RequestResult<GetTraderPnlResponses, GetTraderPnlErrors, ThrowOnError> {
        return (options.client ?? client).get<GetTraderPnlResponses, GetTraderPnlErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/traders/{trader_id}/pnl',
            ...options
        });
    }
    
    /**
     * List position events for a trader
     */
    public static listTraderPositions<ThrowOnError extends boolean = false>(options: Options<ListTraderPositionsData, ThrowOnError>): RequestResult<ListTraderPositionsResponses, ListTraderPositionsErrors, ThrowOnError> {
        return (options.client ?? client).get<ListTraderPositionsResponses, ListTraderPositionsErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/traders/{trader_id}/positions',
            ...options
        });
    }
    
    /**
     * List trades for a trader
     */
    public static listTraderTrades<ThrowOnError extends boolean = false>(options: Options<ListTraderTradesData, ThrowOnError>): RequestResult<ListTraderTradesResponses, ListTraderTradesErrors, ThrowOnError> {
        return (options.client ?? client).get<ListTraderTradesResponses, ListTraderTradesErrors, ThrowOnError>({
            security: [{ name: 'X-API-Key', type: 'apiKey' }],
            url: '/v1/polymarket/traders/{trader_id}/trades',
            ...options
        });
    }
}
