// @ts-nocheck
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://api.radion.app' | (string & {});
};

export type ApiKeyInfo = {
    callCount: number;
    createdAt: string;
    expiresAt?: string | null;
    keyLabel: string;
    lastUsedAt?: string | null;
    monthlyUsage: MonthlyUsage;
    plan: ApiKeyPlan;
    requestsPerSecond: number;
};

export type ApiKeyPlan = 'free' | 'starter' | 'pro' | 'enterprise';

export type Candle = {
    c: string;
    h: string;
    l: string;
    o: string;
    t: number;
    v: string;
};

export type CandlestickResponse = {
    data: Array<Candle>;
};

export type CreateKeyData = {
    keyLabel: string;
    rawKey: string;
};

export type CreateKeyRequest = {
    keyLabel: string;
};

export type CreateKeyResponse = {
    data: CreateKeyData;
};

export type CursorPageEvent = {
    data: Array<{
        category?: string | null;
        closed?: boolean | null;
        description?: string | null;
        endDate?: number | null;
        id: string;
        liquidity?: number | null;
        marketCount: number;
        openInterest?: number | null;
        slug?: string | null;
        startDate?: number | null;
        title?: string | null;
        volume?: number | null;
    }>;
    nextCursor?: string | null;
};

export type CursorPageHolder = {
    data: Array<{
        address: string;
        positionId: string;
        shares: string;
    }>;
    nextCursor?: string | null;
};

export type CursorPageMarket = {
    data: Array<{
        conditionId: string;
        lastPrice: string;
        lastTradeTs?: string | null;
        openInterest: string;
        totalVolume: string;
        tradeCount: number;
        updatedBlock: number;
    }>;
    nextCursor?: string | null;
};

export type CursorPagePosition = {
    data: Array<{
        amount: string;
        blockNumber: number;
        collateralToken?: string | null;
        conditionId: string;
        kind: number;
        logIndex: number;
        parentCollectionId?: string | null;
        positionId?: string | null;
        stakeholder: string;
        ts: string;
        txHash: string;
    }>;
    nextCursor?: string | null;
};

export type CursorPageTrade = {
    data: Array<{
        blockNumber: number;
        builderCode?: string | null;
        chainId: number;
        conditionId: string;
        fee: string;
        logIndex: number;
        maker: string;
        outcomeIndex: number;
        positionId: string;
        price: string;
        side: number;
        size: string;
        taker: string;
        ts: string;
        txHash: string;
        usd: string;
    }>;
    nextCursor?: string | null;
};

export type CursorPageTraderPnl = {
    data: Array<{
        address: string;
        realizedPnl: string;
        tradeCount: number;
        unrealizedPnl: string;
        updatedBlock: number;
        volume: string;
        winCount: number;
    }>;
    nextCursor?: string | null;
};

export type DeleteKeyResponse = {
    ok: boolean;
};

export type ErrorResponse = {
    detail: string;
    request_id: string;
    status: number;
    title: string;
    type: string;
};

export type Event = {
    category?: string | null;
    closed?: boolean | null;
    description?: string | null;
    endDate?: number | null;
    id: string;
    liquidity?: number | null;
    marketCount: number;
    openInterest?: number | null;
    slug?: string | null;
    startDate?: number | null;
    title?: string | null;
    volume?: number | null;
};

export type EventResponse = {
    data: Event;
};

export type GetApiKeyInfoResponse = {
    data: ApiKeyInfo;
};

export type HealthResponse = {
    data: HealthStatus;
};

export type HealthStatus = {
    at: string;
    status: string;
};

export type Holder = {
    address: string;
    positionId: string;
    shares: string;
};

export type KeySummary = {
    createdAt: string;
    keyLabel: string;
    lastUsedAt?: string | null;
    plan: ApiKeyPlan;
};

export type ListKeysResponse = {
    data: Array<KeySummary>;
    monthlyUsage: MonthlyUsage;
    plan: ApiKeyPlan;
    trialEndsAt?: string | null;
};

export type Market = {
    conditionId: string;
    lastPrice: string;
    lastTradeTs?: string | null;
    openInterest: string;
    totalVolume: string;
    tradeCount: number;
    updatedBlock: number;
};

export type MarketBySlug = {
    description?: string | null;
    endDate?: number | null;
    id: string;
    outcomes: Array<Outcome>;
    question?: string | null;
    slug?: string | null;
    startDate?: number | null;
    status: string;
};

export type MarketBySlugResponse = {
    data: MarketBySlug;
};

export type MarketDetail = {
    market: Market;
    resolution?: null | Resolution;
};

export type MarketDetailResponse = {
    data: MarketDetail;
};

export type MonthlyUsage = {
    limit?: number | null;
    resetsAt: string;
    used: number;
};

export type OrderBook = {
    midpoint: number;
    tokenId: string;
};

export type OrderBookResponse = {
    data: OrderBook;
};

export type Outcome = {
    label: string;
    tokenId?: string | null;
};

export type Position = {
    amount: string;
    blockNumber: number;
    collateralToken?: string | null;
    conditionId: string;
    kind: number;
    logIndex: number;
    parentCollectionId?: string | null;
    positionId?: string | null;
    stakeholder: string;
    ts: string;
    txHash: string;
};

export type Resolution = {
    conditionId: string;
    payoutNumerators: Array<number>;
    resolutionSource: number;
    resolvedTs: string;
};

export type SearchResults = {
    markets: Array<Market>;
    traders: Array<TraderPnl>;
};

export type SearchResultsResponse = {
    data: SearchResults;
};

export type Trade = {
    blockNumber: number;
    builderCode?: string | null;
    chainId: number;
    conditionId: string;
    fee: string;
    logIndex: number;
    maker: string;
    outcomeIndex: number;
    positionId: string;
    price: string;
    side: number;
    size: string;
    taker: string;
    ts: string;
    txHash: string;
    usd: string;
};

export type TraderPnl = {
    address: string;
    realizedPnl: string;
    tradeCount: number;
    unrealizedPnl: string;
    updatedBlock: number;
    volume: string;
    winCount: number;
};

export type TraderPnlResponse = {
    data: TraderPnl;
};

export type ListUserKeysData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/keys';
};

export type ListUserKeysErrors = {
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListUserKeysError = ListUserKeysErrors[keyof ListUserKeysErrors];

export type ListUserKeysResponses = {
    /**
     * The user's API keys.
     */
    200: ListKeysResponse;
};

export type ListUserKeysResponse = ListUserKeysResponses[keyof ListUserKeysResponses];

export type CreateApiKeyData = {
    body: CreateKeyRequest;
    path?: never;
    query?: never;
    url: '/auth/keys';
};

export type CreateApiKeyErrors = {
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Access denied.
     */
    403: ErrorResponse;
    /**
     * Resource already exists.
     */
    409: ErrorResponse;
    /**
     * Validation failed.
     */
    422: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type CreateApiKeyError = CreateApiKeyErrors[keyof CreateApiKeyErrors];

export type CreateApiKeyResponses = {
    /**
     * API key created. The raw key is shown once.
     */
    201: CreateKeyResponse;
};

export type CreateApiKeyResponse = CreateApiKeyResponses[keyof CreateApiKeyResponses];

export type DeleteApiKeyData = {
    body?: never;
    path: {
        /**
         * The key label of the key to delete
         */
        keyLabel: string;
    };
    query?: never;
    url: '/auth/keys/{keyLabel}';
};

export type DeleteApiKeyErrors = {
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Access denied.
     */
    403: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type DeleteApiKeyError = DeleteApiKeyErrors[keyof DeleteApiKeyErrors];

export type DeleteApiKeyResponses = {
    /**
     * Key deleted successfully.
     */
    200: DeleteKeyResponse;
};

export type DeleteApiKeyResponse = DeleteApiKeyResponses[keyof DeleteApiKeyResponses];

export type GetApiKeyInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetApiKeyInfoErrors = {
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetApiKeyInfoError = GetApiKeyInfoErrors[keyof GetApiKeyInfoErrors];

export type GetApiKeyInfoResponses = {
    /**
     * Metadata for the currently authenticated API key.
     */
    200: GetApiKeyInfoResponse;
};

export type GetApiKeyInfoResponse2 = GetApiKeyInfoResponses[keyof GetApiKeyInfoResponses];

export type GetHealthStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthStatusResponses = {
    /**
     * Service is healthy and ready to accept traffic.
     */
    200: HealthResponse;
};

export type GetHealthStatusResponse = GetHealthStatusResponses[keyof GetHealthStatusResponses];

export type ListEventsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/events';
};

export type ListEventsErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListEventsError = ListEventsErrors[keyof ListEventsErrors];

export type ListEventsResponses = {
    200: CursorPageEvent;
};

export type ListEventsResponse = ListEventsResponses[keyof ListEventsResponses];

export type GetEventData = {
    body?: never;
    path: {
        /**
         * Event id (numeric) or slug
         */
        identifier: string;
    };
    query?: never;
    url: '/v1/polymarket/events/{identifier}';
};

export type GetEventErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetEventError = GetEventErrors[keyof GetEventErrors];

export type GetEventResponses = {
    200: EventResponse;
};

export type GetEventResponse = GetEventResponses[keyof GetEventResponses];

export type ListMarketsData = {
    body?: never;
    path?: never;
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/markets';
};

export type ListMarketsErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListMarketsError = ListMarketsErrors[keyof ListMarketsErrors];

export type ListMarketsResponses = {
    200: CursorPageMarket;
};

export type ListMarketsResponse = ListMarketsResponses[keyof ListMarketsResponses];

export type GetMarketBySlugData = {
    body?: never;
    path: {
        /**
         * Market slug
         */
        market_slug: string;
    };
    query?: never;
    url: '/v1/polymarket/markets/slug/{market_slug}';
};

export type GetMarketBySlugErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetMarketBySlugError = GetMarketBySlugErrors[keyof GetMarketBySlugErrors];

export type GetMarketBySlugResponses = {
    200: MarketBySlugResponse;
};

export type GetMarketBySlugResponse = GetMarketBySlugResponses[keyof GetMarketBySlugResponses];

export type GetMarketData = {
    body?: never;
    path: {
        /**
         * Market condition id (0x hex)
         */
        condition_id: string;
    };
    query?: never;
    url: '/v1/polymarket/markets/{condition_id}';
};

export type GetMarketErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetMarketError = GetMarketErrors[keyof GetMarketErrors];

export type GetMarketResponses = {
    200: MarketDetailResponse;
};

export type GetMarketResponse = GetMarketResponses[keyof GetMarketResponses];

export type GetMarketCandlestickData = {
    body?: never;
    path: {
        /**
         * Market condition id (0x hex)
         */
        condition_id: string;
    };
    query?: {
        resolution?: string;
        from?: number;
        to?: number;
    };
    url: '/v1/polymarket/markets/{condition_id}/candlestick';
};

export type GetMarketCandlestickErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetMarketCandlestickError = GetMarketCandlestickErrors[keyof GetMarketCandlestickErrors];

export type GetMarketCandlestickResponses = {
    200: CandlestickResponse;
};

export type GetMarketCandlestickResponse = GetMarketCandlestickResponses[keyof GetMarketCandlestickResponses];

export type ListMarketHoldersData = {
    body?: never;
    path: {
        /**
         * Market condition id (0x hex)
         */
        condition_id: string;
    };
    query?: {
        min_shares?: number;
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/markets/{condition_id}/holders';
};

export type ListMarketHoldersErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListMarketHoldersError = ListMarketHoldersErrors[keyof ListMarketHoldersErrors];

export type ListMarketHoldersResponses = {
    200: CursorPageHolder;
};

export type ListMarketHoldersResponse = ListMarketHoldersResponses[keyof ListMarketHoldersResponses];

export type ListMarketTradesData = {
    body?: never;
    path: {
        /**
         * Market condition id (0x hex)
         */
        condition_id: string;
    };
    query?: {
        side?: number;
        outcome?: number;
        trader?: string;
        min_usd?: number;
        max_usd?: number;
        from?: number;
        to?: number;
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/markets/{condition_id}/trades';
};

export type ListMarketTradesErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListMarketTradesError = ListMarketTradesErrors[keyof ListMarketTradesErrors];

export type ListMarketTradesResponses = {
    200: CursorPageTrade;
};

export type ListMarketTradesResponse = ListMarketTradesResponses[keyof ListMarketTradesResponses];

export type GetOrderBookData = {
    body?: never;
    path?: never;
    query: {
        position_id: string;
    };
    url: '/v1/polymarket/order-book';
};

export type GetOrderBookErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetOrderBookError = GetOrderBookErrors[keyof GetOrderBookErrors];

export type GetOrderBookResponses = {
    200: OrderBookResponse;
};

export type GetOrderBookResponse = GetOrderBookResponses[keyof GetOrderBookResponses];

export type SearchData = {
    body?: never;
    path?: never;
    query: {
        q: string;
        type?: string;
    };
    url: '/v1/polymarket/search';
};

export type SearchErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type SearchError = SearchErrors[keyof SearchErrors];

export type SearchResponses = {
    200: SearchResultsResponse;
};

export type SearchResponse = SearchResponses[keyof SearchResponses];

export type GetGlobalPnlData = {
    body?: never;
    path?: never;
    query?: {
        sort_by?: string;
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/traders/global-pnl';
};

export type GetGlobalPnlErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetGlobalPnlError = GetGlobalPnlErrors[keyof GetGlobalPnlErrors];

export type GetGlobalPnlResponses = {
    200: CursorPageTraderPnl;
};

export type GetGlobalPnlResponse = GetGlobalPnlResponses[keyof GetGlobalPnlResponses];

export type GetTraderPnlData = {
    body?: never;
    path: {
        /**
         * Trader address (0x hex)
         */
        trader_id: string;
    };
    query?: never;
    url: '/v1/polymarket/traders/{trader_id}/pnl';
};

export type GetTraderPnlErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type GetTraderPnlError = GetTraderPnlErrors[keyof GetTraderPnlErrors];

export type GetTraderPnlResponses = {
    200: TraderPnlResponse;
};

export type GetTraderPnlResponse = GetTraderPnlResponses[keyof GetTraderPnlResponses];

export type ListTraderPositionsData = {
    body?: never;
    path: {
        /**
         * Trader address (0x hex)
         */
        trader_id: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/traders/{trader_id}/positions';
};

export type ListTraderPositionsErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListTraderPositionsError = ListTraderPositionsErrors[keyof ListTraderPositionsErrors];

export type ListTraderPositionsResponses = {
    200: CursorPagePosition;
};

export type ListTraderPositionsResponse = ListTraderPositionsResponses[keyof ListTraderPositionsResponses];

export type ListTraderTradesData = {
    body?: never;
    path: {
        /**
         * Trader address (0x hex)
         */
        trader_id: string;
    };
    query?: {
        cursor?: string;
        limit?: number;
    };
    url: '/v1/polymarket/traders/{trader_id}/trades';
};

export type ListTraderTradesErrors = {
    /**
     * Invalid request parameters.
     */
    400: ErrorResponse;
    /**
     * Missing or invalid API key.
     */
    401: ErrorResponse;
    /**
     * Rate limit exceeded.
     */
    429: ErrorResponse;
    /**
     * Unexpected server error.
     */
    500: ErrorResponse;
};

export type ListTraderTradesError = ListTraderTradesErrors[keyof ListTraderTradesErrors];

export type ListTraderTradesResponses = {
    200: CursorPageTrade;
};

export type ListTraderTradesResponse = ListTraderTradesResponses[keyof ListTraderTradesResponses];
